# Generated by Django 3.2.23 on 2024-01-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='path',
            field=models.FilePathField(null=True),
        ),
    ]
