# Generated by Django 3.2.23 on 2024-01-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_document_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='path',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
