# Generated by Django 3.2.23 on 2024-01-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0004_alter_document_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.AlterField(
            model_name='document',
            name='path',
            field=models.FilePathField(default='default', null=True),
        ),
    ]
