# Generated by Django 3.2.23 on 2024-01-17 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0005_auto_20240117_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='path',
        ),
    ]
