# Generated by Django 3.2.23 on 2024-01-17 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0007_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
    ]
