# Generated by Django 3.2.23 on 2024-01-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0009_documentfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='abtract',
            field=models.TextField(null=True),
        ),
    ]
