# Generated by Django 3.2.23 on 2024-01-19 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0010_document_abtract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='abtract',
            new_name='abstract',
        ),
    ]
